"""Chatbot service: graph-grounded Q&A with dashboard navigation guidance."""

from typing import Any, Optional

from neo4j import AsyncDriver

from app.llm.base import GenerateConfig, LLMProvider
from app.models.api import Citation, QueryResponse
from app.services.retrieval_service import RetrievalService


DASHBOARD_CONTEXT = """
DASHBOARD NAVIGATION GUIDE:
The digiTwin dashboard has the following pages and features:

- Overview (/): Main dashboard showing key metrics (total decisions, confidence scores,
  pending approvals, blocked actions), recent agent activity, a knowledge graph preview,
  items needing attention, and quick navigation shortcuts.

- Decisions (/decisions): Browse and filter all decisions extracted from ingested artifacts.
  Each card shows title, status (proposed/approved/superseded/rejected), confidence score,
  and owner. Click a decision to see its full lineage graph and impact score.

- Artifacts (/artifacts): View all ingested knowledge sources (transcripts, policy docs,
  PRDs, RFCs, postmortems, contracts, audio, video, GitHub repos). Shows ingestion status
  and allows new uploads via drag-and-drop or URL.

- Ask the Twin (/ask): Full-page conversational Q&A interface with citation support.
  Ask any question about decisions, assumptions, evidence, or policies in the knowledge graph.

- Actions (/actions): Action Center showing draft follow-up messages generated by the AI
  agent. Actions are policy-checked before being allowed. Shows history of all agent actions.

- Resolution (/resolution): Autonomous Resolution Engine — manage cases where the AI
  detects blockers, contradictions, stale approvals, or policy conflicts. Supports
  observe/recommend/auto modes.

- Review Inbox (/review): Human-in-the-loop review queue. Approve or reject agent-proposed
  actions that require human sign-off before execution.

- Permissions (/permissions): Inspect user roles and permissions. Simulate policy changes
  to see what access a user would gain under hypothetical grants or delegations.

- Dependency Map (/dependency-map): Interactive force-directed knowledge graph visualizing
  all nodes (decisions, assumptions, evidence, people, tasks) and their relationships.

- Audit (/audit): Full chronological log of all agent actions with initiator, type, status,
  policy path, and timestamp.

- Timeline (/timeline): Visual timeline of decisions ordered by creation date.

HOW TO USE THE SYSTEM:
- To ingest new knowledge: go to Artifacts, click "Add Artifact", upload a file or paste a URL.
- To query the knowledge base: use Ask the Twin or the chat widget (you are here).
- To approve pending decisions: go to Review Inbox.
- To explore connections between decisions: use the Dependency Map.
- To check what a user can do: go to Permissions and enter their user ID.
- To see why an action was blocked: check the Actions page and inspect the policy path.
"""

CHATBOT_SYSTEM_PROMPT = """You are digiTwin Assistant, a helpful AI embedded in the digiTwin decision intelligence dashboard. You help users in two ways:

1. ANSWERING DATA QUESTIONS: Using the knowledge graph context provided, answer questions about decisions, assumptions, evidence, policies, people, tasks, and artifacts that have been ingested into the system. Cite specific nodes by their ID in square brackets (e.g., [D-abc123]) when referencing them.

2. DASHBOARD GUIDANCE: Help users navigate and use the dashboard. Explain what each page does, how to find information, and how to accomplish tasks within the UI.

Rules:
- For data questions, use ONLY the graph context provided — do not fabricate facts.
- If you cannot answer a data question from the context, say so clearly and suggest the user try the full "Ask the Twin" page (/ask) for deeper queries.
- For navigation/how-to questions, use the Dashboard Navigation Guide below.
- Be concise and direct — this is a quickfire Q&A widget.
- If the question is ambiguous, answer both the data and navigation interpretations briefly.

{dashboard_context}

Graph Context (may be empty if no relevant data was found):
{graph_context}

User Question: {question}

Answer:"""


class ChatbotService:
    def __init__(self, driver: AsyncDriver, llm: LLMProvider) -> None:
        self.driver = driver
        self.llm = llm
        self._retrieval = RetrievalService(driver, llm)

    async def chat(
        self,
        question: str,
        user_id: str,
        top_k: int = 5,
        allowed_scopes: Optional[list[str]] = None,
    ) -> QueryResponse:
        # Attempt graph retrieval — gracefully returns empty list on any failure
        try:
            results: list[dict[str, Any]] = await self._retrieval.hybrid_search(
                question,
                top_k=top_k,
                allowed_scopes=allowed_scopes,
            )
        except Exception:
            results = []

        graph_context_str = self._retrieval._format_context(results) if results else "No relevant graph data found."

        prompt = CHATBOT_SYSTEM_PROMPT.format(
            dashboard_context=DASHBOARD_CONTEXT,
            graph_context=graph_context_str,
            question=question,
        )

        answer = await self.llm.generate(prompt, GenerateConfig(temperature=0.3))

        citations = [
            Citation(
                id=r["id"],
                label=r.get("label", "Node"),
                title=r.get("title", ""),
                excerpt=r.get("content", "")[:200] if r.get("content") else None,
            )
            for r in results
            if r.get("id") and (
                f"[{r['id']}]" in answer
                or f"[{r.get('label', '')}:{r['id']}]" in answer
            )
        ]

        return QueryResponse(
            answer=answer,
            citations=citations,
            graph_context=results if results else None,
        )
